CHKPT:
  CHKPT_SAVING_PERIOD: 5
  DIRECTORY          : experiments/chkpts
  EPOCH_UNSTABLE_END : 40
  FILENAME_PREFIX    : {{ filename_prefix }}
  PATH_CHKPT_PREV    : null
  PRETRAIN           : {{ path_pretrain_chkpt|default('pretrained_chkpts/transfered_weights.resnet50.chkpt') }}
DATASET:
  BATCH_SIZE   : 5
  FRAC_TRAIN   : 0.8
  FRAC_VALIDATE: 1.0
  NUM_WORKERS  : {{ num_workers }}
  PATH         : {{ path_dataset }}
  SAMPLE_SIZE  : {{ sample_size }}
  CXI_KEY:
    num_peaks : "/entry_1/result_1/nPeaks"
    peak_y    : "/entry_1/result_1/peakYPosRaw"
    peak_x    : "/entry_1/result_1/peakXPosRaw"
    data      : "/entry_1/data_1/data"
    mask      : "/entry_1/data_1/mask"
    segmask   : "/entry_1/data_1/segmask"
DDP:
  BACKEND               : nccl
  USES_UNIQUE_WORLD_SEED: true
LOGGING:
  DIRECTORY      : experiments/logs
  FILENAME_PREFIX: {{ filename_prefix }}
LOSS:
  FOCAL:
    ALPHA: 1.0
    GAMMA: 2.0
LR_SCHEDULER:
  LR           : 3e-4
  MIN_LR       : 1e-7
  TOTAL_EPOCHS : 500
  USES_PREV    : true
  WARMUP_EPOCHS: 5
MISC:
  MAX_EPOCHS          : 400
  NUM_GPUS            : {{ num_gpus }}
  NUM_NODES           : {{ num_nodes }}
  USES_MIXED_PRECISION: true
MODEL:
  BIFPN:
    NUM_BLOCKS  : 3
    NUM_FEATURES: 64
    NUM_LEVELS  : 3
  FREEZES_BACKBONE   : false
  USES_RANDOM_WEIGHTS: false
OPTIM:
  GRAD_CLIP   : 1.0
  LR          : 0.0003
  WEIGHT_DECAY: 1e-4
