qos                : "batch"
walltime           : "1:00"
job                : "job_name"
num_nodes          : 1
trainer            : 'train.fsdp.py'
yaml_config        : 'base.yaml'
OMP_NUM_THREADS    : 1
transformers_cache : $HOME/.cache/huggingface
num_gpus_per_node  : 2
num_cpus_per_node  : 2
