CHKPT:
  TIMESTAMP_PREV  : null
  EPOCH_PREV      : null
  DIRECTORY       : chkpts
  PRETRAIN        : "pretrained_chkpts/transfered_weights.resnet50.chkpt"
  FILENAME_PREFIX : null

DATASET:
  PATH           : "datasets/mfx13016_0028_N68+mfxp22820_0013_N37+mfx13016_0028_N63_low_photon.68v37v30.data.label_corrected.npy"
  SAMPLE_SIZE    : 3000
  FRAC_TRAIN     : 0.8
  FRAC_VALIDATE  : 1.0
  BATCH_SIZE     : 5
  NUM_WORKERS    : 5

MODEL:
  BIFPN:
    NUM_BLOCKS   : 1
    NUM_FEATURES : 64
  FREEZES_BACKBONE : false
  USES_RANDOM_WEIGHTS : false

LOSS:
  FOCAL:
    ALPHA : 1.0
    GAMMA : 2.0

OPTIM:
  LR           : 3e-4
  WEIGHT_DECAY : 1e-4

LR_SCHEDULER:
  PATIENCE : 10

DDP:
  BACKEND                : nccl
  USES_UNIQUE_WORLD_SEED : false

LOGGING:
  DIRECTORY       : logs
  FILENAME_PREFIX : null

MISC:
  USES_MIXED_PRECISION : true
  MAX_EPOCHS           : 150
  NUM_GPUS             : 4
